---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    # published_ports:
    #   - 127.0.0.1:9633:9633
    cgroupns_mode: host
    privileged: true

provisioner:
  name: ansible

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
